# Site settings
title: iriseoyoung
email: iris.sy.kang@gmail.com
url: https://iriseoyoung.github.io
baseurl: "/iriseoyoung.github.io"
description: "Iris Kang's artist/maker portfolio website"
keywords: "iriseoyoung, artist, maker, portfolio"
skills: "maker of all sorts - sound artist - etc..."
meta_author: iriseoyoung
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: iris

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000 
  primary-rgb: "0,0,0" #"128,179,255"
  secondary: 92C8B8 #FD6E8A
  secondary-dark: 8C8C8C #A2122F

# Footer settings
footer:
  copyright: iriseoyoung
#  location: Location
#  social: find me elsewhere
#  credits: credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: soundcloud
#    url: https://soundcloud.com/iriseoyoung
#  - title: instagram
#    url: https://www.instagram.com/iriseoyoungg/
#  - title: github
#    url: https://github.com/iriseoyoung

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:title/